import express from 'express';
import helmet from 'helmet';
import cors from 'cors';
import cookieParser from 'cookie-parser';
import pinoHttp from 'pino-http';
import { randomUUID } from 'node:crypto';
import { AuthRepository } from './repositories/auth-repository.js';
import { AuthService } from './services/auth-service.js';
import { AuthController } from './controllers/auth-controller.js';
import { authenticate } from './middlewares/authenticate.js';
import { csrfProtection } from './middlewares/csrf.js';
import { authRoutes } from './routes/auth-routes.js';
import { userRoutes } from './routes/user-routes.js';
import { habitRoutes, dailyPlanRoutes } from './routes/habit-routes.js';
import { journalRoutes } from './routes/journal-routes.js';
import { emotionRoutes, emotionalEventRoutes } from './routes/emotion-routes.js';
import { dashboardRoutes } from './routes/dashboard-routes.js';
import { telemetryRoutes } from './routes/telemetry-routes.js';
import { aiRoutes } from './routes/ai-routes.js';
import { HabitService } from './services/habit-service.js';
import { EmotionService } from './services/emotion-service.js';
import { JournalService } from './services/journal-service.js';
import { DashboardService } from './services/dashboard-service.js';
import { TelemetryService } from './services/telemetry-service.js';
import { AiService } from './services/ai-service.js';
import { HabitController } from './controllers/habit-controller.js';
import { EmotionController } from './controllers/emotion-controller.js';
import { JournalController } from './controllers/journal-controller.js';
import { DashboardController } from './controllers/dashboard-controller.js';
import { TelemetryController } from './controllers/telemetry-controller.js';
import { AiController } from './controllers/ai-controller.js';
import { UserService } from './services/user-service.js';
import { UserController } from './controllers/user-controller.js';
import { errorHandler, notFound, Problem } from './utils/problem.js';

export function createApp({ env, db, tokens, logger, overrides = {} }) {
  const repository = overrides.repository ?? new AuthRepository(db);
  const authService = overrides.authService ?? overrides.service ?? new AuthService({ db, repository, tokens, env });
  const userService = overrides.userService ?? new UserService({ db, env });
  const emotionService = overrides.emotionService ?? new EmotionService({ db });
  const habitService = overrides.habitService ?? new HabitService({ db });
  const journalService = overrides.journalService ?? new JournalService({ db, emotionService });
  const telemetryService = overrides.telemetryService ?? new TelemetryService({ db, emotionService });
  const dashboardService = overrides.dashboardService ?? new DashboardService({ db, habitService, emotionService, telemetryService });
  const aiService = overrides.aiService ?? new AiService({ db, env, userService, journalService, habitService });
  const auth = authenticate({ tokens, repository });
  const authController = new AuthController(authService, env);
  const userController = new UserController(userService);
  const habitController = new HabitController(habitService);
  const emotionController = new EmotionController(emotionService);
  const journalController = new JournalController(journalService);
  const dashboardController = new DashboardController(dashboardService);
  const telemetryController = new TelemetryController(telemetryService);
  const aiController = new AiController(aiService);
  const app = express(); app.set('trust proxy', env.TRUST_PROXY); app.disable('x-powered-by');
  app.use(pinoHttp({ logger, genReqId: (req, res) => { const id = req.headers['x-request-id']?.slice(0, 100) || randomUUID(); res.setHeader('x-request-id', id); return id; } }));
  app.use(helmet());
  app.use(cors({ origin(origin, callback) { if (!origin || env.WEB_ORIGINS.includes(origin)) callback(null, true); else callback(new Problem(403, 'ORIGIN_DENIED', 'Origem não autorizada.')); }, credentials: true }));
  app.use(express.json({ limit: '100kb', type: 'application/json' })); app.use(cookieParser());
  app.use((_req, res, next) => { res.setHeader('Cache-Control', 'no-store'); next(); });
  app.get('/health', (_req, res) => res.json({ data: { status: 'ok' } }));
  app.get('/ready', async (_req, res, next) => { try { await db.raw('SELECT 1'); res.json({ data: { status: 'ready' } }); } catch { next(new Problem(503, 'NOT_READY', 'Serviço temporariamente indisponível.')); } });
  app.use('/api/v1/auth', authRoutes({ controller: authController, authenticate: auth, csrf: csrfProtection(env) }));
  app.use('/api/v1/users', userRoutes({ authenticate: auth, controller: userController }));
  app.use('/api/v1/habits', habitRoutes({ authenticate: auth, controller: habitController }));
  app.use('/api/v1/daily-plan', dailyPlanRoutes({ authenticate: auth, controller: habitController }));
  app.use('/api/v1/journals', journalRoutes({ authenticate: auth, controller: journalController }));
  app.use('/api/v1/emotions/catalog', emotionRoutes({ authenticate: auth, controller: emotionController }));
  app.use('/api/v1/emotions', emotionalEventRoutes({ authenticate: auth, controller: emotionController }));
  app.use('/api/v1/dashboard', dashboardRoutes({ authenticate: auth, controller: dashboardController }));
  app.use('/api/v1/telemetry', telemetryRoutes({ authenticate: auth, controller: telemetryController }));
  app.use('/api/v1/ai', aiRoutes({ authenticate: auth, controller: aiController }));
  app.use(notFound); app.use(errorHandler); return app;
}
